export default {
  theme: {
    extend: {
      colors: {
        muk: "#0D0D10",
        baekja: "#F0EBE3",
        cheongja: "#2DD4BF",
        dancheng: "#E63B2E",
        "seoul-red": "#E63B2E",
        silver: "#C0C0C0",
        gold: "#FABF13",
        "gold-light": "#FABF13",
        "stage-purple": "#8220DC",
        "drop-pink": "#DC1E5A",
        "lab-teal": "#00C9A7",
        "gallery-amber": "#F59E0B",
        ink: "#0D0D0D",
        "warm-white": "#F5F2ED",
        celadon: "#1B2A4A",
        catalyst: "#00FF88",
        "lab-green": "#00B482",
        "gallery-gold": "#A67C00",
        "seoul-pink": "#FF0A73",
        "cheongja-jade": "#00D4B8",
      },
      fontFamily: {
        rubik: ["var(--font-nunito)", "sans-serif"],
        display: ["var(--font-nunito)", "var(--font-barlow)", "sans-serif"],
        impact: ["var(--font-nunito)", "var(--font-barlow)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        space: ["var(--font-space)", "sans-serif"],
        outfit: ["var(--font-inter)", "sans-serif"],
        inter: ["var(--font-inter)", "sans-serif"],
        "noto-kr": ["var(--font-noto-kr)", "sans-serif"],
        playfair: ["var(--font-playfair)", "serif"],
      },
    },
  },
};
